//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LectureAccess.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LectureAccess.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N&apos;a pas pu compacter la base de données.
        ///{0}.
        /// </summary>
        internal static string ERR_CANNOT_COMPACT {
            get {
                return ResourceManager.GetString("ERR_CANNOT_COMPACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur.
        /// </summary>
        internal static string ERR_CAPTION {
            get {
                return ResourceManager.GetString("ERR_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur à la fermeture de la base : .
        /// </summary>
        internal static string ERR_CLOSING {
            get {
                return ResourceManager.GetString("ERR_CLOSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur lors du remplacement de la base de données. La base a été sauvegardée sous :
        ///{0}.
        /// </summary>
        internal static string ERR_DB_COMPRESSION {
            get {
                return ResourceManager.GetString("ERR_DB_COMPRESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un seul fichier à la fois s&apos;il vous plait..
        /// </summary>
        internal static string ERR_ONE_FILE_ONLY {
            get {
                return ResourceManager.GetString("ERR_ONE_FILE_ONLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur lors de la lecture des index..
        /// </summary>
        internal static string ERR_READING_INDEXES {
            get {
                return ResourceManager.GetString("ERR_READING_INDEXES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur à la lecture des relations..
        /// </summary>
        internal static string ERR_READING_RELATIONS {
            get {
                return ResourceManager.GetString("ERR_READING_RELATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compression terminée..
        /// </summary>
        internal static string INF_COMPRESSION_COMPLETE {
            get {
                return ResourceManager.GetString("INF_COMPRESSION_COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} lignes retournées.
        /// </summary>
        internal static string INF_NB_RETURNED_LINES {
            get {
                return ResourceManager.GetString("INF_NB_RETURNED_LINES", resourceCulture);
            }
        }
    }
}
